source 'https://rubygems.org'

gem 'byebug'
gem 'capybara'
gem 'capybara-screenshot'
gem 'chunky_png', '1.3.7'
gem 'cucumber'
gem 'cuke_sniffer'
gem 'dotenv'
gem 'graphql-client'
gem 'graphql-ruby'
gem 'parallel_tests'
gem 'rake'
gem 'report_builder'
gem 'rspec'
gem 'rspec-expectations'
gem 'selenium-webdriver'
gem 'show_me_the_cookies'
gem 'site_prism'
gem 'site_prism-table'
gem 'syntax'
gem 'webdrivers', '~> 3.0'
gem 'rspec-retry'
gem 'cucumber-api'